# Generated by Django 3.0.5 on 2021-04-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0003_kitchen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.TextField(blank=True, default='localhost:8000/media/default.jpg', max_length=200),
        ),
    ]
